// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yoo.Trainees.ShipWars.DataBase;

#nullable disable

namespace Yoo.Trainees.ShipWars.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
<<<<<<<< HEAD:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013131425_Initial.Designer.cs
    [Migration("20231013131425_Initial")]
========
    [Migration("20231013145027_Initial")]
>>>>>>>> feature/TRAINEE-173-play-mode-of-the-game:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013145027_Initial.Designer.cs
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("NextPlayer")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScissorsRockPaperBet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamePlayer");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid>("GamePlayersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayersId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ship");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013131425_Initial.Designer.cs
                            Id = new Guid("37283c82-668f-4d63-a7e4-b54b08d0546c"),
========
                            Id = new Guid("85ce8508-012d-4cec-b19f-7da26443ee95"),
>>>>>>>> feature/TRAINEE-173-play-mode-of-the-game:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013145027_Initial.Designer.cs
                            Length = 1,
                            Name = "Submarine"
                        },
                        new
                        {
<<<<<<<< HEAD:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013131425_Initial.Designer.cs
                            Id = new Guid("224bae5a-3245-4896-a000-f5acbdee6eb8"),
========
                            Id = new Guid("f9e8c834-2b20-4f05-a96d-993c70e055bf"),
>>>>>>>> feature/TRAINEE-173-play-mode-of-the-game:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013145027_Initial.Designer.cs
                            Length = 2,
                            Name = "Destroyer"
                        },
                        new
                        {
<<<<<<<< HEAD:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013131425_Initial.Designer.cs
                            Id = new Guid("a4fad743-eeb2-4c08-a47e-fdb178d97544"),
========
                            Id = new Guid("1c33868c-d693-4343-92eb-583e78ca53b3"),
>>>>>>>> feature/TRAINEE-173-play-mode-of-the-game:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013145027_Initial.Designer.cs
                            Length = 3,
                            Name = "Cruiser"
                        },
                        new
                        {
<<<<<<<< HEAD:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013131425_Initial.Designer.cs
                            Id = new Guid("ed1eb044-3d2b-4486-bdc9-3b3c90b2cc42"),
========
                            Id = new Guid("adf1162d-6589-4ffb-9bd9-3a25fbc088c4"),
>>>>>>>> feature/TRAINEE-173-play-mode-of-the-game:Yoo.Trainees.WarShip/Backend/Yoo.Trainees.ShipWars/Yoo.Trainees.ShipWars.DataBase/Migrations/20231013145027_Initial.Designer.cs
                            Length = 4,
                            Name = "Warship"
                        });
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.ShipPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipPosition");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Shot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Shot");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.GamePlayer", b =>
                {
                    b.HasOne("Yoo.Trainees.ShipWars.DataBase.Entities.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yoo.Trainees.ShipWars.DataBase.Entities.Player", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Message", b =>
                {
                    b.HasOne("Yoo.Trainees.ShipWars.DataBase.Entities.GamePlayer", "GamePlayers")
                        .WithMany()
                        .HasForeignKey("GamePlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.ShipPosition", b =>
                {
                    b.HasOne("Yoo.Trainees.ShipWars.DataBase.Entities.GamePlayer", "GamePlayer")
                        .WithMany()
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yoo.Trainees.ShipWars.DataBase.Entities.Ship", "Ship")
                        .WithMany("Positions")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePlayer");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Shot", b =>
                {
                    b.HasOne("Yoo.Trainees.ShipWars.DataBase.Entities.GamePlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Game", b =>
                {
                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Player", b =>
                {
                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("Yoo.Trainees.ShipWars.DataBase.Entities.Ship", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
